[package]
name = "mist"
version = "0.1.0"
authors = ["TmLev <sololev27@gmail.com>"]
edition = "2018"

[lib]
name = "mist"
path = "src/lib.rs"

[[bin]]
name = "simulations"
path = "src/simulations.rs"

[dependencies]
