[package]
name = "mist"
version = "0.1.0"
authors = ["TmLev <sololev27@gmail.com>"]
edition = "2018"

[lib]
name = "mist"
path = "src/lib.rs"

[dependencies]
actix = "0.11.0-beta.1"
actix-rt = "2.0.0-beta.1"
